spring:
  datasource:
    url: jdbc:mysql://
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false #빈값은 직렬화하지 않음
server:
  port: 8081